apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-uptime-server
spec:
  replicas: 1
  selector:
    matchLabels:
      project: cloud-uptime-server
  template:
    metadata:
      labels:
        project: cloud-uptime-server
    spec:
      containers:
      - env:
        image: uptime-server:1
        imagePullPolicy: Always
        name: cloud-uptime-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
